{
 "title": "Infra Metrics - oTeL v3",
 "time": { "from": "2026-01-05T19:20:34.384Z", "to": "2026-01-05T19:29:11.382Z" },
 "refresh": "5s",
 "panels": [
  { "title": "Infra-metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    { "expr": "system_cpu_load_average_1m", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Used (GB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gb" } },
   "targets": [
    {
     "expr": "system_memory_usage_bytes{state=\"used\"}/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory free (GB)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage_bytes{state=\"free\"}/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "system_memory_usage_bytes/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk - Read",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (system_disk_operations_total{direction=\"read\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk - Write",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (system_disk_operations_total{direction=\"write\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU process_cpu_time_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "otelcol_process_cpu_seconds_total{}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}